refactor: changed env var names
digilandbali/digilandbali-web pull request #58
Opened 2022-08-15 08:34 UTC by ical10

## Describe your changes
Added missing env which will be removed once wagmi is fully integrated

## Issue ticket number / link
No issue ticket, minor fix

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] If it is a core feature, I have added thorough tests.
- [x] Will this be part of a product update? If yes, please write one phrase about this update.

2022-08-15 08:55 UTC, irmannmal requested changes

2022-08-15 08:55 UTC, irmannmal commented on next.config.js
> +    providerKey: process.env.NEXT_PUBLIC_PROVIDER_KEY,
change to `web3ProviderKey: process.env.NEXT_PUBLIC_WEB3_PROVIDER_KEY`

2022-08-15 08:55 UTC, irmannmal commented on next.config.js
> +    providerURL: process.env.NEXT_PUBLIC_ALCHEMY_URL,
change to `web3ProviderURL: process.env.NEXT_PUBLIC_WEB3_PROVIDER_URL`

2022-08-15 08:55 UTC, irmannmal commented on next.config.js
>      contractAddress: process.env.NEXT_PUBLIC_LBSF_CONTRACT_ADDRESS,
change to `lbsfContractAddress: process.env.NEXT_PUBLIC_LBSF_CONTRACT_ADDRESS`

2022-08-15 08:55 UTC, irmannmal commented on next.config.js
> +    apiURL: process.env.DIGILANDBALI_API_URL ?? 'http://localhost:3001',
change to `apiURL: process.env.API_URL ?? 'http://localhost:3001',

2022-08-15 08:56 UTC, irmannmal commented
bor @ical10, don't forget to update [.env-template](https://github.com/digilandbali/digilandbali-web/blob/main/.env-template)

2022-08-15 09:41 UTC, ical10 commented
please recheck @irmannmal

2022-08-16 01:20 UTC, irmannmal approved these changes

2022-08-16 01:21 UTC, merged